### PR TITLE
Add files from tape image

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Hello @quentinnuk and @JohnForecast,

This pull request adds POWER.BCL and removes the MUD.MIC.jpg scan.

It also updates MUD.MIC and MBOOTS.MAC to the verisions on the tape, but I'm not sure if they are better than the chnages @quentinnuk added recently.

### CODE REVIEW

**Comment by quentinnuk** [comment]
@larsbrinkhoff @JohnForecast I agree we should use the files on the tape. I will be doing a test build with the tape files shortly and will then be able to confirm if it builds OK.

**Comment by quentinnuk** [comment]
@larsbrinkhoff @JohnForecast I have successfully completed a test build from source and have got the DBASE exe built to create the database files from MUD.TXT. Unfortunately when I run the built MUD.EXE, on my system all it does is (note the missing identifier at the start of the sentence too):

```
.ru mud

isn't available at the moment. Try again tomorrow?
```

**Comment by JohnForecast** [comment]
> On Apr 9, 2018, at 5:59 PM, quentinnuk <notifications@github.com> wrote:
> 
> @larsbrinkhoff <https://github.com/larsbrinkhoff> @JohnForecast <https://github.com/JohnForecast> I have successfully completed a test build from source and have got the DBASE exe built to create the database files from MUD.TXT. Unfortunately when I run the built MUD.EXE, on my system all it does is (note the missing identifier at the start of the sentence too):
> 
> .ru mud
> 
> isn't available at the moment. Try again tomorrow?

That’s about as far as I got. Essex had strict limits on when MUD could be run and I suspect it is failing because of that check. The trick is probably to set the variable “maint” non-zero which will bypass the time check. There’s a routine access() in MUDLIB.BCL which does the checking but I haven’t worked out what it does yet, my BCPL is extremely rusty - I haven’t used it since 1974!

**Comment by larsbrinkhoff** [comment]
So everyone's ok with the files in this pull request?  If so, I'll merge it.

**Comment by quentinnuk** [comment]
@larsbrinkhoff @JohnForecast I agree merge it. Incidentally here is my latest output having messed about a bit:

`.ru mud 


 
ESSEX UNIVERSITY: Multi-User Dungeon
                                     
This Mud created: 28th February 1984 at 20:50:58
Welcome! By what name shall I call you?
*
`

Im not yet sure I know how I got it to work, but it involved using some files from the source zip and some form that tape. They are different versions of the muddle which causes issues, but I got lucky. I'll update my blog when I have worked out how I got it to work.

**Comment by JohnForecast** [comment]
> On Apr 10, 2018, at 6:41 PM, quentinnuk <notifications@github.com> wrote:
> 
> @larsbrinkhoff <https://github.com/larsbrinkhoff> @JohnForecast <https://github.com/JohnForecast> I agree merge it. Incidentally here is my latest output having messed about a bit:
> 
> 
	I agree - go ahead and merge it.

> `.ru mud
> 
> ESSEX UNIVERSITY: Multi-User Dungeon
> 
> This Mud created: 28th February 1984 at 20:50:58
> Welcome! By what name shall I call you?
> *
> `
> 
> Im not yet sure I know how I got it to work, but it involved using some files from the source zip and some form that tape. They are different versions of the muddle which causes issues, but I got lucky. I'll update my blog when I have worked out how I got it to work.
> 
> 
	I would have expected the tape and, maybe, the zip file to be self-consistent since they were likely produced from a working source tree.

**Comment by larsbrinkhoff** [comment]
Done, thanks.

**Pull request merged**
